[2024-06-27T22:54:31.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:54:31.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T22:54:21.225530+00:00 [queued]>
[2024-06-27T22:54:31.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T22:54:21.225530+00:00 [queued]>
[2024-06-27T22:54:31.202+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-27T22:54:31.216+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-27 22:54:21.225530+00:00
[2024-06-27T22:54:31.220+0000] {standard_task_runner.py:63} INFO - Started process 5763 to run task
[2024-06-27T22:54:31.223+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-27T22:54:21.225530+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmp4g_ic07z']
[2024-06-27T22:54:31.225+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask tsk_is_file_in_s3_available
[2024-06-27T22:54:31.259+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T22:54:21.225530+00:00 [running]> on host ip-172-31-6-214.us-east-2.compute.internal
[2024-06-27T22:54:31.334+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T22:54:21.225530+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T22:54:21.225530+00:00'
[2024-06-27T22:54:31.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:54:31.347+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-27T22:54:31.348+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024225424.csv
[2024-06-27T22:54:31.352+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-27T22:54:31.353+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-27T22:54:36.756+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024225424.csv
[2024-06-27T22:54:41.764+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024225424.csv
[2024-06-27T22:54:41.777+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-27T22:54:41.778+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:54:41.782+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-27T22:54:21.225530+00:00, execution_date=20240627T225421, start_date=20240627T225431, end_date=20240627T225441
[2024-06-27T22:54:41.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:54:41.817+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:54:41.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
