[2024-06-27T23:15:00.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:15:00.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:14:51.079003+00:00 [queued]>
[2024-06-27T23:15:00.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:14:51.079003+00:00 [queued]>
[2024-06-27T23:15:00.080+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:15:00.095+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-27 23:14:51.079003+00:00
[2024-06-27T23:15:00.099+0000] {standard_task_runner.py:63} INFO - Started process 5886 to run task
[2024-06-27T23:15:00.102+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-27T23:14:51.079003+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmphfmr9sp0']
[2024-06-27T23:15:00.104+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask tsk_is_file_in_s3_available
[2024-06-27T23:15:00.140+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:14:51.079003+00:00 [running]> on host ip-172-31-6-214.us-east-2.compute.internal
[2024-06-27T23:15:00.215+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T23:14:51.079003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T23:14:51.079003+00:00'
[2024-06-27T23:15:00.215+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:15:00.228+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-27T23:15:00.229+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024231453.csv
[2024-06-27T23:15:00.234+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-27T23:15:00.234+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-27T23:15:05.648+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024231453.csv
[2024-06-27T23:15:10.659+0000] {s3.py:117} INFO - Poking for key : s3://clean-data-csv-bucket/response_data_27062024231453.csv
[2024-06-27T23:15:10.670+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-27T23:15:10.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:15:10.675+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-27T23:14:51.079003+00:00, execution_date=20240627T231451, start_date=20240627T231500, end_date=20240627T231510
[2024-06-27T23:15:10.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:15:10.717+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:15:10.722+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
